name: Unit Tests
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.1
          target: esp32s3
          command: GITHUB_ACTIONS="true" idf.py build
          path: 'test-ci'

      - name: Run tests
        uses: bitaxeorg/esp32-qemu-test-action@main
        with:
          path: 'test-ci'

      - name: Upload event file
        uses: actions/upload-artifact@v4
        with:
          name: event-file
          path: ${{ github.event_path }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: report.xml