name: Publish Test Results
on:
  workflow_run:
    workflows: ["Unit Tests"]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}

    steps:
      - name: Download all artifacts
        run: |
          mkdir artifacts
          cd artifacts
          gh api "${{ github.event.workflow_run.artifacts_url }}" \
            -q '.artifacts[] | [.name, .archive_download_url] | @tsv' \
          | while IFS=$'\t' read name url; do
              gh api "$url" --jq .archive_download_url > "$name.zip"
              unzip -q "$name.zip" -d "$name"
            done

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_name: ${{ github.event.workflow_run.event }}
          event_file: artifacts/event-file/event.json
          files: artifacts/test-results/**/*.xml
